import { Header } from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Sidebar } from "../components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "blog-uam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Header />
      <div className="grid h-full w-full grid-cols-12 place-items-center">
        {children}
        <Sidebar />
      </div>
    </html>
  );
}
